import random

def execute(message=None):
    facts = [
        "The first computer virus, 'Brain,' was created in 1986 by two Pakistani brothers.",
        "Python was named after the British comedy series 'Monty Python's Flying Circus.'",
        "The first website ever created is still online at info.cern.ch.",
        "Google was originally called 'Backrub.'",
        "The first hard disk drive could hold only 5MB of data.",
        "The 'QWERTY' keyboard layout was designed in 1873 to slow down typing on mechanical typewriters.",
        "Email existed before the World Wide Web.",
        "The first webcam was used to monitor a coffee pot at the University of Cambridge.",
        "There are over 700 programming languages in the world.",
        "The first Apple logo featured Sir Isaac Newton sitting under an apple tree.",
        "The Apollo 11 computer had less processing power than today's smartphones.",
        "Bill Gates wrote his first computer program at age 13.",
        "The 'Ctrl+Alt+Del' command was created by IBM engineer David Bradley.",
        "The first domain name ever registered was 'symbolics.com' in 1985.",
        "The floppy disk was invented by IBM in 1967.",
        "CAPTCHA stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart.'",
        "The first known programmer was Ada Lovelace, who worked on Charles Babbage's Analytical Engine.",
        "Steve Jobs was fired from Apple in 1985, the company he co-founded.",
        "The first computer game, 'Spacewar!,' was created in 1962.",
        "The term 'bug' in computing was inspired by an actual moth found in a computer in 1947.",
        "The '@' symbol was chosen for email addresses because it was rarely used in computing at the time.",
        "The first SMS message, sent in 1992, simply said 'Merry Christmas.'",
        "Over 90% of the world's currency exists only in digital form.",
        "Mark Zuckerberg created Facebook in his Harvard dorm room in 2004.",
        "The first version of Microsoft Windows was released in 1985.",
        "The Eiffel Tower has its own Twitter account.",
        "The first computer weighed over 27 tons and occupied 1,800 square feet.",
        "The first mobile phone call was made in 1973 by Martin Cooper.",
        "The 'thumbs up' emoji is the most-used emoji worldwide.",
        "HTML was invented by Tim Berners-Lee in 1991.",
        "The first computer mouse was made of wood.",
        "Linux was created by Linus Torvalds in 1991 as a hobby project.",
        "The average person spends over 6 hours a day using the internet.",
        "Amazon was originally an online bookstore.",
        "The first video ever uploaded to YouTube was titled 'Me at the zoo.'",
        "Twitter was originally called 'Twttr.'",
        "More than 3.5 billion Google searches are made every day.",
        "The longest word you can type using only your left hand on a QWERTY keyboard is 'stewardesses.'",
        "The Unicode standard has over 143,000 characters.",
        "The world's first 1TB hard drive was released in 2007.",
        "The term 'spam' for unwanted email comes from a Monty Python sketch.",
        "The concept of 'cloud computing' dates back to the 1960s.",
        "Over 500 hours of video are uploaded to YouTube every minute.",
        "The first smartphone, IBM Simon, was released in 1994.",
        "The average smartphone user checks their phone over 100 times a day.",
        "More than 2 billion websites exist on the internet today.",
        "Bluetooth is named after a 10th-century Scandinavian king, Harald 'Bluetooth' Gormsson.",
        "Over 90% of the world's data was created in the last two years.",
        "Typing 'Google in 1998' in Google search shows the website's original design."
    ]
    return random.choice(facts)
